using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SmartAdmin.WebUI.Models
{
    public class ar_electronic_invoice
    {
        [Key]
        public int n_document_no { get; set; }
        public int n_DataAreaID { get; set; }
        public Nullable<int> n_invoice_type_id { get; set; }
        public string d_document_date { get; set; }
        public Nullable<int> n_customer_id { get; set; }
        public Nullable<int> n_sales_Man_id { get; set; }
        public Nullable<int> n_acc_dir_id { get; set; }
        public Nullable<int> n_store_id { get; set; }
        public Nullable<int> n_cash_id { get; set; }
        public Nullable<int> n_Bank_id { get; set; }
        public Nullable<int> n_store_serial { get; set; }
        public Nullable<int> n_month_serial { get; set; }
        public Nullable<int> n_serial_inv_type { get; set; }
        public string s_cost_center_id { get; set; }
        public string s_cost_center_id2 { get; set; }
        public Nullable<decimal> n_currency_coff { get; set; }
        public string s_description_arabic { get; set; }
        public string s_description_eng { get; set; }
        public Nullable<int> n_currency_id { get; set; }
        public Nullable<int> n_no_of_items { get; set; }
        public Nullable<decimal> n_total_value { get; set; }
        public Nullable<decimal> n_total_discount { get; set; }
        public Nullable<decimal> n_Discount_ratio { get; set; }
        public Nullable<decimal> n_extra_discount { get; set; }
        public Nullable<decimal> n_extra_expenses { get; set; }
        public Nullable<decimal> n_net_value { get; set; }
        public Nullable<bool> b_has_extra_discount { get; set; }
        public Nullable<bool> b_has_extra_expnses { get; set; }
        public Nullable<bool> b_use_multi_cost_center { get; set; }
        public Nullable<bool> b_using_multi_store { get; set; }
        public Nullable<int> n_UserAdd { get; set; }
        public string d_UserAddDate { get; set; }
        public Nullable<int> n_UserUpdate { get; set; }
        public string d_UserUpdateDate { get; set; }
        public Nullable<bool> b_Deleted { get; set; }
        public Nullable<int> n_trans_source_no { get; set; }
        public string d_due_date { get; set; }
        public string d_date_transaction { get; set; }
        public Nullable<decimal> n_Cash_Value { get; set; }
        public Nullable<decimal> n_CreditCard_Value { get; set; }
        public Nullable<int> n_Credit_Card_No { get; set; }
        public Nullable<decimal> n_Paid { get; set; }
        public Nullable<int> n_Shift_no { get; set; }
        public Nullable<int> n_CardType_id { get; set; }
        public Nullable<bool> b_is_service { get; set; }
        public Nullable<int> n_curr_replicated_id { get; set; }
        public string d_curr_sys_date { get; set; }
        public Nullable<bool> b_is_concrete { get; set; }
        public Nullable<decimal> n_sales_Tax { get; set; }
        public Nullable<decimal> n_discount_tax { get; set; }
        public Nullable<decimal> _n_discount_tax_ratio { get; set; }
        public Nullable<decimal> n_additional_tax { get; set; }
        public Nullable<decimal> n_additional_tax_ratio { get; set; }
        public Nullable<int> n_invoice_category_id { get; set; }
        public Nullable<int> n_category_serial { get; set; }
        public Nullable<decimal> n_discount_tax_ratio { get; set; }
        public Nullable<int> n_site_id { get; set; }
        public string s_direct_customer_name { get; set; }
        public Nullable<bool> b_InvoiceWithoutBonus { get; set; }
        public Nullable<bool> b_TaxesInvoice_Discount { get; set; }
        public Nullable<decimal> n_TaxesDiscount_Ratio { get; set; }
        public Nullable<decimal> n_SalesTaxes_Default { get; set; }
        public Nullable<decimal> n_HealthMinistry_Discount { get; set; }
        public Nullable<decimal> n_Bonus_Discount { get; set; }
        public Nullable<decimal> n_over_Discount { get; set; }
        public Nullable<decimal> n_over2_Discount { get; set; }
        public Nullable<decimal> n_total_advanced_payment { get; set; }
        public string s_tafkita { get; set; }
        public Nullable<int> n_Marbel_workType { get; set; }
        public Nullable<bool> b_maintenance { get; set; }
        public string d_FromDate { get; set; }
        public string d_ToDate { get; set; }
        public Nullable<decimal> n_Customer_NetValue { get; set; }
        public Nullable<int> n_qoutation_no { get; set; }
        public Nullable<bool> b_manager_confirmed { get; set; }
        public Nullable<decimal> n_total_qty { get; set; }
        public Nullable<decimal> n_advance_payment { get; set; }
        public Nullable<decimal> n_net_value_after_advance { get; set; }
        public Nullable<bool> b_deducted_from_tax { get; set; }
        public Nullable<bool> b_Is_Advance_payment { get; set; }
        public Nullable<int> n_customer_DataAreaID { get; set; }
        public Nullable<decimal> n_retention_percent { get; set; }
        public Nullable<decimal> n_retention_value { get; set; }
        public Nullable<decimal> n_net_with_retention { get; set; }
        public string s_po_no { get; set; }
        public string s_quotations_codes { get; set; }
        public string s_deliveries_codes { get; set; }
        public Nullable<int> n_patient_no { get; set; }
        public string s_Time { get; set; }
        public Nullable<int> n_patient_in_trans_no { get; set; }
        public Nullable<bool> b_clinic_internal { get; set; }
        public Nullable<int> n_clinic_no { get; set; }
        public Nullable<decimal> n_patient_loaded { get; set; }
        public Nullable<decimal> n_Company_laoded { get; set; }
        public Nullable<decimal> n_pnt_extra_Load { get; set; }
        public Nullable<decimal> n_comp_extra_discount { get; set; }
        public Nullable<int> n_current_year { get; set; }
        public Nullable<int> n_current_company { get; set; }
        public Nullable<int> n_current_branch { get; set; }
        public string s_book_no { get; set; }
        public string s_customer_tel { get; set; }
        public string s_Table_No { get; set; }
        public Nullable<int> n_Order_No { get; set; }
        public Nullable<bool> n_TicketClosed { get; set; }
        public Nullable<int> n_pepoleNO { get; set; }
        public Nullable<int> n_waiter_id { get; set; }
        public Nullable<int> n_dr_no { get; set; }
        public Nullable<decimal> n_current_points { get; set; }
        public Nullable<decimal> n_Withdrawal_points { get; set; }
        public string s_additional_notes { get; set; }
        public Nullable<decimal> n_Guarantee_detained { get; set; }
        public Nullable<int> n_return_invoice_no { get; set; }
        public Nullable<decimal> n_return_invoice_value { get; set; }
        public string s_identity { get; set; }
        public Nullable<decimal> n_net_value_after_expenses_tax { get; set; }
        public string s_invoice_hid { get; set; }
        public Nullable<decimal> n_salsManComm { get; set; }
        public Nullable<decimal> n_WeightValue { get; set; }
        public Nullable<bool> b_Delivered { get; set; }
        public Nullable<bool> b_is_press { get; set; }
        public Nullable<decimal> n_bank_CommisionTax { get; set; }
        public Nullable<decimal> n_bank_Commision_value { get; set; }
        public Nullable<decimal> n_FractionsDiff_Value { get; set; }
        public Nullable<int> n_DataAreaIDFrom { get; set; }
        public Nullable<int> n_repair_doc_no { get; set; }
        public string s_Receiptnumber { get; set; }
        public Nullable<int> n_Customs_Service_no { get; set; }
        public string s_port { get; set; }
        public string s_expenses_descrip { get; set; }
        public string s_revenue_descrip { get; set; }
        public string s_custom_no { get; set; }
        public string d_custom_date { get; set; }
        public string s_policy_no { get; set; }
        public string s_policy_new_no { get; set; }
        public string s_containers_no { get; set; }
        public string s_goods_num { get; set; }
        public string s_goods_type { get; set; }
        public string s_Import_docNO { get; set; }
        public string d_Import_docDate { get; set; }
        public Nullable<bool> b_total_policy_price { get; set; }
        public Nullable<decimal> n_drivers_commissions { get; set; }
        public Nullable<decimal> n_salesman_commission { get; set; }
        public Nullable<bool> b_sales_discount { get; set; }
        public string SerializedFormdata { get; set; }
        public string WebNots { get; set; }
        public Nullable<int> n_closed_no { get; set; }
        public Nullable<int> n_invoice_resturant_type { get; set; }
        public Nullable<decimal> n_manual_sales_tax { get; set; }
        public Nullable<int> n_portNo { get; set; }
        public Nullable<decimal> n_expenses_commissions { get; set; }
        public Nullable<int> n_fridge_code { get; set; }
        public Nullable<bool> b_stop_item_discount { get; set; }
        public Nullable<decimal> n_expenses_tax { get; set; }
        public Nullable<int> n_agent_id { get; set; }
        public Nullable<bool> b_delivery { get; set; }
        public string s_address { get; set; }
        public string d_Delivere_date { get; set; }
        public Nullable<int> n_user_Delivered { get; set; }
        public Nullable<int> n_customer_tax_type { get; set; }
        public Nullable<bool> b_is_ceramics { get; set; }
        public Nullable<bool> b_from_renew_contract { get; set; }
        public Nullable<int> n_status { get; set; }
        public Nullable<int> n_fabric_order_type { get; set; }
        public Nullable<int> n_fabric_order_no { get; set; }
        public string s_tax_ref_no { get; set; }
        public Nullable<int> n_user_send_to_tax_auth { get; set; }
        public string d_send_to_tax_auth_date { get; set; }
        public Nullable<bool> b_Reviewed { get; set; }
        public string s_delivery_note_no { get; set; }
        public string d_delivery_note_date { get; set; }
        public string s_work_order_no { get; set; }
        public string d_work_order_date { get; set; }
        public string s_order_no { get; set; }
        public string d_order_date { get; set; }
        public Nullable<int> n_cust_agreement_no { get; set; }
        public Nullable<int> n_cust_agreement_installment_no { get; set; }
        public Nullable<int> n_delivery_id { get; set; }
        public string n_electronic_ref_invoice_no { get; set; }
        public Nullable<bool> b_send { get; set; }
        public Nullable<bool> b_prepare_to_send_taxInv { get; set; }
        public byte[] s_signature { get; set; }
        public string d_signature_date { get; set; }
        public string d_supply_date { get; set; }
        public Nullable<bool> b_mobile { get; set; }
        public Nullable<int> n_print_count { get; set; }
        public string d_confirm_date { get; set; }
        public string d_cancel_confirm_date { get; set; }
        public Nullable<int> n_confirm_user_id { get; set; }
        public Nullable<int> n_cancel_confirm_user_id { get; set; }
        public Nullable<int> n_identity_serial { get; set; }
        public Nullable<bool> b_rest_print_to_customer { get; set; }
        public Nullable<int> n_project_id { get; set; }
        public string s_delivery_notes { get; set; }
        public string s_notes1 { get; set; }
        public string s_notes2 { get; set; }
        public string s_notes3 { get; set; }
        public Nullable<bool> b_closed_by_supervisor { get; set; }
        public Nullable<int> n_refund_reason_id { get; set; }
        public Nullable<bool> b_Guarantee_deducted_from_tax { get; set; }
        public Nullable<int> n_supplier_id { get; set; }
        public string s_scr_car_no { get; set; }
        public string s_scr_driver_name { get; set; }
    }
}
