using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace SmartAdmin.WebUI.Models
{
    public class sc_items_details
    {
        [Key]
        public int n_Id { get; set; }
        public string s_item_id { get; set; }
        public int n_DataAreaID { get; set; }
        public string s_main_item_id { get; set; }
        public string s_serial { get; set; }
        public string s_item_name { get; set; }
        public string s_item_name_eng { get; set; }
        public string s_arabic_item_description { get; set; }
        public string s_english_item_description { get; set; }
        public Nullable<int> n_MinmumUnit { get; set; }
        public Nullable<int> n_item_type_id { get; set; }
        public Nullable<int> n_classA_no { get; set; }
        public Nullable<int> n_classB_no { get; set; }
        public Nullable<int> n_classC_no { get; set; }
        public Nullable<bool> b_item_using_sales_tax { get; set; }
        public Nullable<int> n_sales_tax_rate { get; set; }
        public Nullable<bool> b_item_using_tip_tax { get; set; }
        public Nullable<bool> b_use_p_x_date { get; set; }
        public string d_production_date { get; set; }
        public string d_expiry_date { get; set; }
        public Nullable<decimal> n_selling_price { get; set; }
        public Nullable<decimal> n_cost_price { get; set; }
        public Nullable<int> n_selling_unit { get; set; }
        public Nullable<int> n_purchasing_unit { get; set; }
        public Nullable<int> n_storing_unit { get; set; }
        public Nullable<int> n_basic_currency_id { get; set; }
        public string s_item_bar_code { get; set; }
        public Nullable<int> n_tip_tax_rate { get; set; }
        public Nullable<int> n_static_period { get; set; }
        public Nullable<int> n_lower_limit { get; set; }
        public Nullable<int> n_reorder_limit { get; set; }
        public Nullable<int> n_ItemSaleMothed { get; set; }
        public Nullable<int> n_maximum_limit { get; set; }
        public Nullable<bool> b_use_stock_limits { get; set; }
        public Nullable<int> n_lower_limit_trans_allow { get; set; }
        public Nullable<int> n_reorder_limit_trans_allow { get; set; }
        public Nullable<int> n_maximum_limit_trans_allow { get; set; }
        public Nullable<bool> b_over_draft { get; set; }
        public Nullable<bool> b_is_grouped { get; set; }
        public Nullable<int> n_on_eye_re { get; set; }
        public string d_curr_sys_date { get; set; }
        public Nullable<int> n_curr_replicated_id { get; set; }
        public Nullable<int> n_curr_closed_id { get; set; }
        public string s_curr_user_id { get; set; }
        public string s_main_supplier_id { get; set; }
        public Nullable<decimal> n_last_p_price { get; set; }
        public Nullable<int> n_evaluation_price { get; set; }
        public string d_date_transaction { get; set; }
        public string s_pics_path { get; set; }
        public Nullable<decimal> n_Sal_p { get; set; }
        public Nullable<decimal> n_pur_p { get; set; }
        public Nullable<decimal> n_stor_p { get; set; }
        public Nullable<bool> b_multi_units_p { get; set; }
        public string s_Sal_p1 { get; set; }
        public string s_Pur_p1 { get; set; }
        public string s_stor_p1 { get; set; }
        public Nullable<bool> b_multi_barcode { get; set; }
        public string s_barcode_sel { get; set; }
        public string s_barcode_pur { get; set; }
        public string s_barcode_stor { get; set; }
        public Nullable<decimal> n_safe_limit { get; set; }
        public Nullable<decimal> n_safe_allow { get; set; }
        public Nullable<int> n_main_unit { get; set; }
        public Nullable<int> n_DistributorCompany_id { get; set; }
        public Nullable<int> n_ManufacturerCompany_id { get; set; }
        public Nullable<int> n_Scientific_id { get; set; }
        public Nullable<int> n_Location_id { get; set; }
        public Nullable<int> n_category_id { get; set; }
        public Nullable<int> n_DrugType { get; set; }
        public Nullable<int> n_Manufacturing_type_id { get; set; }
        public Nullable<int> n_expire_period { get; set; }
        public Nullable<bool> b_lot_controlled { get; set; }
        public Nullable<bool> n_have_alternative_item { get; set; }
        public Nullable<int> n_stock_tacking_id { get; set; }
        public Nullable<decimal> n_Customer_Price { get; set; }
        public string s_closes_model_year { get; set; }
        public string s_closes_model_no { get; set; }
        public Nullable<int> n_ROW_MATRIAL { get; set; }
        public Nullable<int> n_property_id { get; set; }
        public Nullable<int> n_closes_model_year { get; set; }
        public Nullable<int> n_serial { get; set; }
        public Nullable<int> n_closes_model_no { get; set; }
        public Nullable<bool> b_general_item { get; set; }
        public Nullable<decimal> n_discount_With_Suppliar { get; set; }
        public Nullable<bool> b_use_Exchange_items { get; set; }
        public Nullable<bool> b_use_Return_Cash { get; set; }
        public Nullable<int> n_Period_Of_Exchange_items { get; set; }
        public Nullable<int> n_Period_Of_Return_cash { get; set; }
        public Nullable<int> n_depart_no { get; set; }
        public Nullable<bool> b_Protected { get; set; }
        public Nullable<bool> b_treatmentOff { get; set; }
        public Nullable<decimal> n_BasicPur_price { get; set; }
        public Nullable<bool> b_itemBranched { get; set; }
        public Nullable<int> n_unit_part2 { get; set; }
        public Nullable<int> n_unit_part1 { get; set; }
        public string s_ItemDesc { get; set; }
        public Nullable<bool> b_row_material { get; set; }
        public string s_GroupItem_no { get; set; }
        public Nullable<decimal> n_ProfitWithcost { get; set; }
        public Nullable<decimal> n_Min_selling_price { get; set; }
        public Nullable<decimal> n_MIN_ProfitWithcost { get; set; }
        public string s_itemNo { get; set; }
        public Nullable<int> n_ReportUnit { get; set; }
        public Nullable<int> n_Parm_ReportUnit { get; set; }
        public Nullable<int> n_status { get; set; }
        public Nullable<int> n_Current_Store { get; set; }
        public Nullable<decimal> n_Price1 { get; set; }
        public Nullable<decimal> n_Price2 { get; set; }
        public string s_arabic_item_descrip { get; set; }
        public Nullable<int> n_dis_pharmay { get; set; }
        public Nullable<int> n_dis_bouns { get; set; }
        public string s_note { get; set; }
        public Nullable<int> n_Forign_Currency { get; set; }
        public Nullable<int> n_currency_type { get; set; }
        public Nullable<decimal> n_Price3 { get; set; }
        public Nullable<decimal> n_lowest_cost { get; set; }
        public Nullable<int> s_Main_Group { get; set; }
        public string s_account_no { get; set; }
        public Nullable<int> n_low_Qty { get; set; }
        public Nullable<bool> b_service { get; set; }
        public Nullable<int> n_convert3 { get; set; }
        public Nullable<int> n_convert2 { get; set; }
        public Nullable<int> n_convert1 { get; set; }
        public Nullable<decimal> n_Car_FirstPur_price { get; set; }
        public Nullable<decimal> n_Volume { get; set; }
        public Nullable<decimal> n_weight { get; set; }
        public Nullable<long> n_Customs_ratio { get; set; }
        public Nullable<bool> b_has_Addon { get; set; }
        public Nullable<int> s_item_no { get; set; }
        public string s_damage_eng { get; set; }
        public Nullable<int> n_static_time { get; set; }
        public string s_cost_center_id { get; set; }
        public Nullable<bool> b_stop { get; set; }
        public Nullable<int> n_country { get; set; }
        public Nullable<bool> b_ProductItem { get; set; }
        public string d_purchase_date { get; set; }
        public string d_arrive_date { get; set; }
        public string d_inform_date { get; set; }
        public string s_estimated_time { get; set; }
        public Nullable<int> n_minute { get; set; }
        public Nullable<int> n_day { get; set; }
        public Nullable<int> n_hour { get; set; }
        public Nullable<decimal> n_po_price { get; set; }
        public string d_RecordDate { get; set; }
        public Nullable<bool> b_bouns_item { get; set; }
        public Nullable<int> n_health_dis_precent { get; set; }
        public Nullable<decimal> n_price_ratio { get; set; }
        public string d_doc_date { get; set; }
        public Nullable<int> n_sum { get; set; }
        public Nullable<decimal> n_direct_expens { get; set; }
        public Nullable<decimal> n_UnitPrice { get; set; }
        public Nullable<decimal> n_CostIncome_ratio { get; set; }
        public Nullable<bool> b_heater { get; set; }
        public Nullable<int> n_heater_qty { get; set; }
        public Nullable<decimal> n_heater_cost { get; set; }
        public Nullable<decimal> n_heater_sellPrice { get; set; }
        public Nullable<decimal> n_heater_CostPrice { get; set; }
        public Nullable<decimal> n_heater_direct_exp { get; set; }
        public Nullable<bool> b_under_work { get; set; }
        public string s_parent { get; set; }
        public Nullable<decimal> n_width { get; set; }
        public Nullable<int> n_height { get; set; }
        public Nullable<bool> b_direct_item { get; set; }
        public Nullable<int> n_itemcategory { get; set; }
        public Nullable<int> n_itemconfig { get; set; }
        public Nullable<bool> b_have_alternative_item { get; set; }
        public Nullable<decimal> n_Parm_sellingUnit { get; set; }
        public Nullable<decimal> n_Parm_purchaseUnit { get; set; }
        public Nullable<decimal> n_Parm_storingUnit { get; set; }
        public Nullable<int> n_unit_id { get; set; }
        public Nullable<bool> b_Deleted { get; set; }
        public string d_UserUpdateDate { get; set; }
        public Nullable<int> n_UserUpdate { get; set; }
        public string d_UserAddDate { get; set; }
        public Nullable<int> n_UserAdd { get; set; }
        public Nullable<decimal> n_manual_cost { get; set; }
        public string s_template_name { get; set; }
        public string s_item_con_code { get; set; }
        public Nullable<int> n_supplier_id { get; set; }
        public Nullable<int> n_project_id { get; set; }
        public Nullable<int> n_store_id { get; set; }
        public Nullable<decimal> n_diameter { get; set; }
        public string s_Item_Desc { get; set; }
        public string s_other { get; set; }
        public string s_agreement_no { get; set; }
        public Nullable<decimal> n_Purchase_Price { get; set; }
        public Nullable<decimal> n_keep_period { get; set; }
        public Nullable<decimal> n_wait_period { get; set; }
        public Nullable<decimal> n_discount_ratio { get; set; }
        public Nullable<int> n_taxes_type { get; set; }
        public Nullable<bool> b_is_stopped { get; set; }
        public Nullable<bool> b_ItemWithoutBonus { get; set; }
        public Nullable<int> n_color { get; set; }
        public Nullable<int> n_size { get; set; }
        public Nullable<bool> b_has_dimension { get; set; }
        public string s_factory_code { get; set; }
        public string s_Revenue_account { get; set; }
        public string s_Expense_account { get; set; }
        public string s_cost_center_id2 { get; set; }
        public Nullable<decimal> n_HealthMinistry_Discount_Ratio { get; set; }
        public Nullable<decimal> n_over_Discount_Ratio { get; set; }
        public Nullable<decimal> n_Bonus_Discount_Ratio { get; set; }
        public Nullable<bool> b_tax_deductible { get; set; }
        public Nullable<int> n_size_type { get; set; }
        public Nullable<decimal> n_VAT { get; set; }
        public string s_purchase_account { get; set; }
        public string dExpireDate { get; set; }
        public string sBatchNo { get; set; }
        public string s_item_place { get; set; }
        public string s_scientific_name { get; set; }
        public Nullable<decimal> n_item_sell_price { get; set; }
        public Nullable<decimal> n_item_purchase_price { get; set; }
        public Nullable<decimal> n_cash_sell_price { get; set; }
        public Nullable<decimal> n_profit_margin { get; set; }
        public string s_old_item_id { get; set; }
        public Nullable<int> n_max_qty_unit_id { get; set; }
        public Nullable<decimal> n_max_unit_qty { get; set; }
        public Nullable<int> n_related_supplier_id { get; set; }
        public Nullable<int> n_current_year { get; set; }
        public Nullable<int> n_current_company { get; set; }
        public Nullable<int> n_current_branch { get; set; }
        public Nullable<int> n_model_no { get; set; }
        public string s_board_no { get; set; }
        public string s_car_notes { get; set; }
        public Nullable<int> n_item_comp_id { get; set; }
        public string s_branches { get; set; }
        public Nullable<bool> b_without_expiredate { get; set; }
        public Nullable<bool> b_not_return_invoice { get; set; }
        public Nullable<decimal> n_sales_percent { get; set; }
        public string s_brand { get; set; }
        public string s_Old_Item_Code { get; set; }
        public string s_Manufacturer_Number { get; set; }
        public string s_Machine_Type { get; set; }
        public string s_item_specifications { get; set; }
        public Nullable<int> n_max_car_parts { get; set; }
        public string s_alternative_code_1 { get; set; }
        public string s_alternative_code_2 { get; set; }
        public string s_alternative_code_3 { get; set; }
        public string s_alternative_code_4 { get; set; }
        public string s_alternative_code_5 { get; set; }
        public string s_alternative_code_6 { get; set; }
        public string s_alternative_codes { get; set; }
        public Nullable<int> n_from_model { get; set; }
        public Nullable<int> n_to_model { get; set; }
        public string s_models { get; set; }
        public Nullable<bool> b_is_warrenty { get; set; }
        public Nullable<decimal> n_length { get; set; }
        public Nullable<bool> b_isDamage { get; set; }
        public Nullable<decimal> n_warranty_period { get; set; }
        public string s_Warranty_Terms { get; set; }
        public string s_SearchInItem { get; set; }
        public string s_mark_name_eng { get; set; }
        public string s_mark_id { get; set; }
        public Nullable<decimal> n_FixingExpectedTime { get; set; }
        public string s_size { get; set; }
        public Nullable<int> n_CarPartsNumber { get; set; }
        public string s_CarPartsNumber { get; set; }
        public Nullable<int> n_selective_tax_type { get; set; }
        public Nullable<decimal> n_selective_tax_percent { get; set; }
        public Nullable<bool> b_Multi_Models { get; set; }
        public Nullable<bool> b_no_discount { get; set; }
        public string s_mastercontrol_f { get; set; }
        public Nullable<decimal> n_mastercontrol_GSM { get; set; }
        public Nullable<decimal> n_mastercontrol_TL { get; set; }
        public Nullable<decimal> n_mastercontrol_TW { get; set; }
        public Nullable<decimal> n_mastercontrol_TH { get; set; }
        public Nullable<int> n_mastercontrol_type { get; set; }
        public Nullable<int> n_mastercontrol_style { get; set; }
        public string s_mastercontrol_notes { get; set; }
        public Nullable<decimal> n_mastercontrol_material_Price { get; set; }
        public Nullable<decimal> n_mastercontrol_sh_T { get; set; }
        public Nullable<decimal> n_mastercontrol_sh_W { get; set; }
        public Nullable<int> n_customer_id { get; set; }
        public Nullable<int> n_play { get; set; }
        public Nullable<int> n_material_type { get; set; }
        public Nullable<decimal> n_paper_width { get; set; }
        public string s_item_bar_code_2 { get; set; }
        public Nullable<decimal> n_AgentPrice { get; set; }
        public Nullable<decimal> n_p_h { get; set; }
        public Nullable<decimal> n_p_f { get; set; }
        public Nullable<decimal> n_p_f2 { get; set; }
        public Nullable<int> n_print_of_color { get; set; }
        public Nullable<decimal> n_discount_tax { get; set; }
        public Nullable<int> n_related_asset_id { get; set; }
        public Nullable<decimal> n_carton_gram { get; set; }
        public string s_tray { get; set; }
        public string s_international_classification_code { get; set; }
        public string s_tax_authority_code { get; set; }
        public Nullable<decimal> n_price_changing_operator { get; set; }
        public string s_item_bar_code_3 { get; set; }
        public string s_item_bar_code_4 { get; set; }
        public Nullable<int> n_finishing { get; set; }
        public Nullable<int> n_Corrugate { get; set; }
        public string s_item_id_zid { get; set; }
        public string s_medical_receipe { get; set; }
        public string s_relative_tax_discount_acc { get; set; }
        public Nullable<bool> b_external_maintainance { get; set; }
        public Nullable<int> n_workorder_shad_no { get; set; }
        public Nullable<bool> b_allow_edit_price_in_rest { get; set; }
        public Nullable<bool> b_open_quantity_default_in_rest { get; set; }
        public Nullable<bool> b_is_comment { get; set; }
        public string s_item_printer_name { get; set; }
        public Nullable<bool> b_reserved { get; set; }
        public Nullable<int>  n_reserve_type { get; set; }
        public Nullable<bool> b_pending { get; set; }
        public string s_damage { get; set; }
        public Nullable<bool> b_invoice { get; set; }
    }
}
